
// Unified type definitions with consistent string IDs and strict typing

export interface BaseEntity {
  id: string;
  created_at?: string;
  updated_at?: string;
}

export interface ProductVariant {
  size?: string;
  color?: string;
  material?: string;
  stock: number;
}

export interface Product extends BaseEntity {
  title: string;
  description: string;
  price: number;
  originalPrice?: number;
  categoryId: string;
  categoryName: string;
  rating: number;
  reviews: number;
  inStock: boolean;
  image: string | null;
  images: string[];
  variants: ProductVariant[];
  features: string[];
  brand: string;
  tags: string[];
  slug?: string;
}

export interface BidHistory {
  bidder: string;
  amount: number;
  time: string;
}

export interface Auction extends BaseEntity {
  title: string;
  description?: string;
  currentBid: number;
  startingBid: number;
  endTime: Date;
  bidders: number;
  category: string;
  condition: string;
  image: string | null;
  bidHistory?: BidHistory[]; // Made optional for listing page
  slug?: string;
}

export interface ServicePortfolioItem {
  id: string;
  providerId: string;
  title: string;
  description: string;
  image: string;
  images?: string[];
  category: string;
  tags?: string[];
  projectDate?: string;
  clientName?: string;
  projectUrl?: string;
  featured?: boolean;
  displayOrder?: number;
  testimonial?: string;
  beforeImage?: string;
  afterImage?: string;
  projectValue?: number;
  createdAt?: string;
  autoGenerated?: boolean;
  sourceProjectId?: string;
  sourceType?: 'manual' | 'project' | 'imported';
}

export interface ServiceReview {
  id: string;
  clientName: string;
  rating: number;
  comment: string;
  date: string;
  verified: boolean;
}

export interface ServiceProvider extends BaseEntity {
  name: string;
  avatar: string | null;
  rating: number;
  reviews: number;
  experience: string;
  location: string;
  phone: string;
  email: string;
  bio: string;
  specialties?: string[];
  certifications?: string[];
  responseTime?: string;
  completedProjects?: number;
  portfolio?: ServicePortfolioItem[];
  recentReviews?: ServiceReview[];
  slug?: string;
  years_in_business?: number;
  awards?: string[];
  work_philosophy?: string;
  portfolio_description?: string;
}

export interface Service extends BaseEntity {
  title: string;
  provider: string;
  rating: number;
  reviews: number;
  startingPrice: number;
  duration: string;
  category: string; // Changed from enum to string for database compatibility
  location: string;
  available: boolean;
  image: string | null;
  description: string;
  features: string[];
  images: string[];
  providerDetails: ServiceProvider;
  availableTimes: string[];
  providerRating?: number;
  responseTime?: string;
  slug?: string;
  faqs?: { question: string; answer: string; }[];
  customizationOptions?: {
    name: string;
    type: 'select' | 'input' | 'textarea';
    options?: string[];
    required: boolean;
    description?: string;
  }[];
}

// Updated booking types with string IDs
export interface BookingData {
  selectedDate: string;
  selectedTime: string;
  customizations: Record<string, string>;
  contactInfo: {
    name: string;
    email: string;
    phone: string;
    message: string;
  };
  agreedToTerms: boolean;
}

export interface ServiceForBooking {
  id: string;
  title: string;
  startingPrice: number;
  duration: string;
  provider: string;
  providerEmail: string;
  customizationOptions?: {
    name: string;
    type: 'select' | 'input' | 'textarea';
    options?: string[];
    required: boolean;
    description?: string;
  }[];
}

export interface EnhancedServiceBookingCardProps {
  service: ServiceForBooking;
  availableTimes: string[];
  onBooking: (bookingData: BookingData) => void;
}

// Updated communication types with string IDs
export interface CommunicationRequest {
  id: string;
  type: 'message' | 'consultation' | 'quote';
  referenceNumber: string;
  timestamp: Date;
  status: 'sent' | 'delivered' | 'read' | 'responded' | 'completed';
  
  customerName: string;
  customerEmail: string;
  customerPhone?: string;
  
  providerId: string;
  providerName: string;
  providerEmail: string;
  
  serviceContext?: {
    serviceId?: string; // Changed from number to string
    serviceName?: string;
    servicePrice?: number;
  };
  
  subject?: string;
  message: string;
  additionalData?: Record<string, any>;
  
  providerResponse?: string;
  responseTimestamp?: Date;
  estimatedResponseTime?: string;
}

export interface NotificationTemplate {
  type: 'customer_confirmation' | 'provider_notification' | 'status_update';
  subject: string;
  htmlContent: string;
  textContent: string;
}

// Project/Showcase types
export interface ShowcaseCard {
  id: string;
  slug: string;
  title: string;
  description: string;
  full_description?: string;
  fullDescription?: string;
  image_path?: string;
  imageUrl?: string;
  tags?: string[];
  participants?: Array<{ id: string; name: string; role: string; avatar?: string; bio?: string }>;
  links?: Array<{ type: string; url: string }>;
  created_at?: string;
  updated_at?: string;
}

export interface Project extends ShowcaseCard {
  purpose?: string;
  expected_impact?: string;
  associations?: string[];
}

// Participant type
export interface Participant extends BaseEntity {
  name: string;
  slug: string;
  bio?: string;
  avatar_path?: string;
  avatar?: string; // Legacy compat
  contact_email?: string;
  contactEmail?: string; // Legacy compat
  contact_phone?: string;
  contactPhone?: string; // Legacy compat
  location?: string;
  skills?: string[];
  experience_level?: string;
  experienceLevel?: string; // Legacy compat
  interests?: string[];
  time_commitment?: string;
  timeCommitment?: string; // Legacy compat
  contributions?: string[];
  availability?: string;
  profile_completed?: boolean;
  is_public?: boolean;
  auth_user_id?: string;
  website?: string;
  social_links?: any;
  socialLinks?: any; // Legacy compat
  personal_links?: any;
  personalLinks?: any; // Legacy compat
  roles?: string[];
  projects?: any[];
  media?: any[];
  howFoundUs?: string;
}

// Sponsor type
export interface Sponsor extends BaseEntity {
  name: string;
  type: 'main' | 'partner' | 'supporter';
  logo?: string;
  website?: string;
  description?: string;
  contactEmail?: string;
  contactPhone?: string;
  contactPerson?: string;
}
